# Generated by Django 2.2.5 on 2019-09-27 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=20)),
                ('message', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=3000)),
                ('technology', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='image')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=20)),
                ('speciality', models.CharField(max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to='home.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='image')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=20)),
                ('technologies', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('reg_numb', models.IntegerField()),
                ('biography', models.TextField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='home.Project')),
            ],
        ),
    ]
