# Generated by Django 2.2.5 on 2019-10-02 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191001_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='home.Supervisor'),
        ),
    ]
