# Generated by Django 2.2.5 on 2019-10-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='departements',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='student',
            name='biography',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='student',
            name='technologies',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='telephone',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='email',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='speciality',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='telephone',
            field=models.CharField(max_length=80),
        ),
    ]
