# Generated by Django 2.2.5 on 2019-10-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191015_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='departements',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
