# Generated by Django 2.2.5 on 2019-10-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20191015_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='post',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
