# Generated by Django 2.2.5 on 2019-10-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_supervisor_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='biography',
            field=models.TextField(max_length=1000),
        ),
    ]
